import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Providers from "./components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Swadisht-a food ordering website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Providers>
        <div className="bg-primary w-full min-h-screen p-5 border-8 border-secondary rounded-lg">
          {/* Navbar */}
          <Navbar />

          {/* Content */}
          <div className="mt-8">
            {children}
          </div>
          <Footer />
        </div>
        </Providers>

      </body>
    </html>
  );
}
